import { useEffect, useState } from 'react'
import { request } from './api'

type Metric = { job: string; method: string; pool_size: number; precision_at_5: number; ndcg_at_5: number }
type Benchmark = { role: string; warm_median_ms: number; cold_retrieval_ms: number; full_match_ms: number; retrieved: number }
type Evaluation = {
  metrics: Metric[]
  benchmarks: Benchmark[]
  snapshot: { benchmark_candidates: number; benchmark_spans: number; current_candidates: number; current_spans: number; current_fts_rows: number }
  import_verification: { source_rows: number; outcomes: { imported: number; duplicate: number; invalid: number; failed?: number }; exact_source_documents: number; bad_offsets: number; import_seconds: number; peak_process_rss_mb: number }
  repeat_import: { imported: number; duplicate: number; invalid: number; failed: number; duration_seconds: number } | null
  source_link_checks: { checked: number; failures: number }
  citation_audit: { claims_reviewed: number; quotes_checked: number; quote_integrity_failures: unknown[]; semantic_judgments: Record<string, number> }
  gap_status_audit: { reviewed: number; possible_false_negatives: number; observations: { candidate_id: number; requirement: string; saved_status: string; judgment: string; observation: string }[] }
  functional_validation: { five_questions: boolean; gateway_citation_checked: number; review_fallback: boolean; chat_fallback: boolean; labeled_question_benchmark: null }
  category_coverage: { category: string; candidates: number; indexed_spans: number; candidates_with_spans: number }[]
  category_scope: string
  category_proxy: { generated_utc: string; shared_candidates: number; method: string; categories: { category: string; candidate_count: number; keyword: { precision_at_5: number; ndcg_at_5: number }; hybrid: { precision_at_5: number; ndcg_at_5: number } }[] }
  judgment_method: string
  disclosure: string
}

const roleName = (key: string) => key.split('_').map(word => word === 'hr' || word === 'it' ? word.toUpperCase() : word[0].toUpperCase() + word.slice(1)).join(' ')
const delta = (left: number, right: number, digits: number) => { const difference = right - left; return `${difference > 0 ? '+' : ''}${difference.toFixed(digits)}` }
const keyboardScroll = (event: React.KeyboardEvent<HTMLDivElement>) => {
  if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') {
    event.preventDefault()
    event.currentTarget.scrollLeft += event.key === 'ArrowRight' ? 120 : -120
  }
}

export default function EvaluationPage() {
  const [data, setData] = useState<Evaluation | null>(null)
  const [error, setError] = useState('')
  const [version, setVersion] = useState(0)
  useEffect(() => {
    let live = true
    setData(null); setError('')
    request<Evaluation>('/api/evaluation').then(value => { if (live) setData(value) }).catch((e: Error) => { if (live) setError(e.message) })
    return () => { live = false }
  }, [version])
  if (error) return <div className="state-panel error" role="alert"><strong>Could not load Evaluation.</strong><p>{error}</p><button onClick={() => setVersion(n => n + 1)}>Retry</button></div>
  if (!data) return <div className="state-panel" role="status">Loading saved evaluation and live coverageâ€¦</div>
  const roles = Array.from(new Set(data.metrics.map(item => item.job)))
  const firstImport = data.import_verification
  const accounted = Object.values(firstImport.outcomes).reduce((sum, count) => sum + count, 0)
  const hrKeyword = data.metrics.find(item => item.job === 'hr_analyst' && item.method === 'keyword')
  const hrHybrid = data.metrics.find(item => item.job === 'hr_analyst' && item.method === 'hybrid')
  return <div className="page-content evaluation-page">
    <div className="section-intro"><span className="eyebrow">EVALUATION / MEASUREMENT SNAPSHOT</span><h1>What the evidence supports.</h1><p>Saved ranking and latency results used {data.snapshot.benchmark_candidates.toLocaleString()} indexed candidates. This local database now contains {data.snapshot.current_candidates.toLocaleString()} candidates after later private uploads. The two counts describe different moments.</p></div>
    <nav className="eval-nav" aria-label="Evaluation sections"><a href="#ranking">Ranking quality</a><a href="#scale">Scale & ingestion</a><a href="#performance">Performance</a><a href="#reliability">Evidence</a><a href="#functional">Chat checks</a><a href="#coverage">Coverage</a><a href="#methodology">Methodology</a></nav>
    <div className="disclosure" role="note"><strong>Exploratory, implementer-judged results.</strong> Three roles have 18 judged candidates each, drawn from keyword and hybrid results plus nonmatches. The HR Analyst hybrid nDCG@5 regressed from {hrKeyword?.ndcg_at_5.toFixed(3)} to {hrHybrid?.ndcg_at_5.toFixed(3)}. These results do not measure hiring accuracy, fairness, or full-corpus recall.</div>

    <section id="ranking" className="surface eval-section"><div className="surface-heading"><div><span className="eyebrow">01 / RANKING QUALITY</span><h2>Keyword versus hybrid</h2></div><span>Saved 2,484-candidate snapshot</span></div><p>Each role has 18 implementer-judged candidates. Grades 2â€“3 of 0â€“3 count as relevant for Precision@5. nDCG@5 compares ordering against the ideal ordering within that judged pool.</p>
      <p className="table-scroll-hint">Scroll sideways to see all columns.</p><div className="category-table-wrap" role="region" aria-label="Ranking quality table" tabIndex={0} onKeyDown={keyboardScroll}><table className="category-table eval-ranking-table"><thead><tr><th scope="col">Role</th><th scope="col">Keyword P@5</th><th scope="col">Hybrid P@5</th><th scope="col">Î” P@5</th><th scope="col">Keyword nDCG@5</th><th scope="col">Hybrid nDCG@5</th><th scope="col">Î” nDCG@5</th></tr></thead><tbody>{roles.map(role => { const keyword = data.metrics.find(item => item.job === role && item.method === 'keyword')!; const hybrid = data.metrics.find(item => item.job === role && item.method === 'hybrid')!; const regression = hybrid.ndcg_at_5 < keyword.ndcg_at_5; return <tr key={role} className={regression ? 'eval-regression-row' : ''}><th scope="row">{roleName(role)}{regression && <span className="eval-regression-tag">Regression</span>}</th><td>{keyword.precision_at_5.toFixed(2)}</td><td>{hybrid.precision_at_5.toFixed(2)}</td><td className={hybrid.precision_at_5 < keyword.precision_at_5 ? 'regression' : ''}>{delta(keyword.precision_at_5, hybrid.precision_at_5, 2)}</td><td>{keyword.ndcg_at_5.toFixed(3)}</td><td>{hybrid.ndcg_at_5.toFixed(3)}</td><td className={regression ? 'regression' : ''}>{delta(keyword.ndcg_at_5, hybrid.ndcg_at_5, 3)}</td></tr> })}</tbody></table></div>
      <p className="eval-callout"><strong>HR Analyst caveat.</strong> Analytics-heavy resumes can outrank recruiting evidence; conservative handling of study or exposure can also lower a relevant profile. The saved HR nDCG@5 regression is a reason to review the ranking and expand blind judgments.</p>
    </section>

    <section id="scale" className="surface eval-section"><div className="surface-heading"><div><span className="eyebrow">02 / SCALE & INGESTION</span><h2>Every primary row accounted for</h2></div><span>First and repeat import jobs</span></div><div className="eval-stat-grid"><div><strong>{firstImport.source_rows.toLocaleString()}</strong><span>Primary CSV rows</span></div><div><strong>{firstImport.outcomes.imported.toLocaleString()}</strong><span>New on first import</span></div><div><strong>{firstImport.outcomes.duplicate.toLocaleString()}</strong><span>Duplicates</span></div><div><strong>{firstImport.outcomes.invalid.toLocaleString()}</strong><span>Invalid</span></div><div><strong>{(firstImport.outcomes.failed || 0).toLocaleString()}</strong><span>Failed</span></div></div><p>{accounted === firstImport.source_rows ? 'All input rows have an explicit outcome.' : 'Outcome totals need investigation.'} The first import took <strong>{firstImport.import_seconds.toFixed(2)} s</strong> and reached <strong>{firstImport.peak_process_rss_mb.toLocaleString()} MB</strong> peak process RSS. Its {firstImport.exact_source_documents.toLocaleString()} distinct CSV documents retained exact source text; the offset audit found {firstImport.bad_offsets} broken spans.</p><p>{data.repeat_import ? `A saved repeat import took ${data.repeat_import.duration_seconds.toFixed(2)} s: ${data.repeat_import.imported} new, ${data.repeat_import.duplicate.toLocaleString()} duplicate, ${data.repeat_import.invalid} invalid, ${data.repeat_import.failed} failed.` : 'Repeat-import timing: Not measured in the available job records.'} The historical benchmark had {data.snapshot.benchmark_spans.toLocaleString()} indexed spans. The current database has {data.snapshot.current_spans.toLocaleString()} spans and {data.snapshot.current_fts_rows.toLocaleString()} FTS entries.</p></section>

    <section id="performance" className="surface eval-section"><div className="surface-heading"><div><span className="eyebrow">03 / PERFORMANCE</span><h2>Saved single-process timings</h2></div><span>Hardware SKU not recorded</span></div><p>Local Windows process, 2,484-candidate snapshot. The first cold retrieval includes model and vector-matrix loading; subsequent role â€œcoldâ€ values occur after that load. Warm values are medians of five calls per role. These are saved measurements, not a new benchmark on the current database.</p><p className="table-scroll-hint">Scroll sideways to see all columns.</p><div className="category-table-wrap" role="region" aria-label="Retrieval latency table" tabIndex={0} onKeyDown={keyboardScroll}><table className="category-table"><thead><tr><th scope="col">Role</th><th scope="col">Cold retrieval</th><th scope="col">Warm retrieval median</th><th scope="col">Full 30-candidate match</th></tr></thead><tbody>{data.benchmarks.map(item => <tr key={item.role}><th scope="row">{roleName(item.role)}</th><td>{(item.cold_retrieval_ms / 1000).toFixed(item.cold_retrieval_ms >= 1000 ? 2 : 3)} s</td><td>{item.warm_median_ms.toFixed(1)} ms</td><td>{item.full_match_ms.toFixed(1)} ms</td></tr>)}</tbody></table></div><p className="eval-small"><strong>Not measured:</strong> p95 latency, concurrent-load throughput, full-corpus recall, and the exact hardware configuration. A warm local median is not a service-level guarantee.</p></section>

    <section id="reliability" className="surface eval-section"><div className="surface-heading"><div><span className="eyebrow">04 / EVIDENCE RELIABILITY</span><h2>Link integrity and claim meaning</h2></div></div><div className="eval-stat-grid"><div><strong>{data.source_link_checks.checked - data.source_link_checks.failures}/{data.source_link_checks.checked}</strong><span>Automated source links valid</span></div><div><strong>{data.citation_audit.claims_reviewed}</strong><span>Manual semantic claims</span></div><div><strong>{data.gap_status_audit.reviewed}</strong><span>Manual gap/status items</span></div></div><p>The automated check verified quote, span, candidate, and source linkage across displayed results. A separate implementer review judged {data.citation_audit.semantic_judgments.supports_requirement} claims contextually supported, {data.citation_audit.semantic_judgments.correctly_uncertain} appropriately uncertain, and {data.citation_audit.semantic_judgments.mention_only} a mention only. A valid quote does not prove proficiency.</p><p>The seven-item gap/status spot check found {data.gap_status_audit.possible_false_negatives} possible machine-learning false negative: a Random Forest project appeared in source while an exact-phrase rule saved â€œNo evidence.â€ Python and SQL skills-list mentions were treated as mentions, not verified work depth. This is a targeted implementer audit, not an error-rate estimate.</p><p className="table-scroll-hint">Scroll sideways to see all columns.</p><div className="category-table-wrap" role="region" aria-label="Seven-item manual gap and status audit" tabIndex={0} onKeyDown={keyboardScroll}><table className="category-table eval-audit-table"><thead><tr><th scope="col">Candidate ID</th><th scope="col">Requirement</th><th scope="col">Saved status</th><th scope="col">Manual reading</th></tr></thead><tbody>{data.gap_status_audit.observations.map((item, index) => <tr key={index}><th scope="row">{item.candidate_id}</th><td>{item.requirement}</td><td>{item.saved_status.replace('_', ' ')}</td><td>{item.observation}{item.judgment === 'possible_false_negative' ? ' Â· Possible false negative' : ''}</td></tr>)}</tbody></table></div></section>

    <section id="functional" className="surface eval-section"><div className="surface-heading"><div><span className="eyebrow">05 / CHAT & FALLBACK</span><h2>Workflow checks, not answer accuracy</h2></div></div><ul className="eval-check-list"><li>{data.functional_validation.five_questions ? 'Passed' : 'Not verified'}: browser flow for all five capstone recruiter questions, including ranking, skill conjunction, gaps, match explanation, and mandatory filter.</li><li>{data.functional_validation.gateway_citation_checked} live gateway citation validated against an owned source span in the saved integration check.</li><li>{data.functional_validation.chat_fallback && data.functional_validation.review_fallback ? 'Passed' : 'Not verified'}: chat and evidence brief showed distinct evidence-only fallback when gateway access failed.</li></ul><p><strong>Labeled question benchmark: Not measured.</strong> There is no independently labeled question set, so citation validity, appropriate refusal, per-question-type accuracy, and fallback correctness rates cannot be claimed from these functional checks.</p></section>

    <section id="coverage" className="eval-section"><div className="surface"><div className="surface-heading"><div><span className="eyebrow">06 / COVERAGE DIAGNOSTICS</span><h2>Live indexing by dataset category</h2></div><span>{data.category_coverage.length} groups</span></div><p>Live counts for {data.category_scope}. Source passages show indexing coverage, not relevance to a job. Later uploads can add an â€œUploadedâ€ group.</p><p className="table-scroll-hint">Scroll sideways to see all columns.</p><div className="category-table-wrap" role="region" aria-label="Live category coverage table" tabIndex={0} onKeyDown={keyboardScroll}><table className="category-table"><thead><tr><th scope="col">Category</th><th scope="col">Candidates</th><th scope="col">With spans</th><th scope="col">Indexed spans</th></tr></thead><tbody>{data.category_coverage.map(item => <tr key={item.category}><th scope="row">{item.category}</th><td>{item.candidates.toLocaleString()}</td><td>{item.candidates_with_spans.toLocaleString()} / {item.candidates.toLocaleString()}</td><td>{item.indexed_spans.toLocaleString()}</td></tr>)}</tbody></table></div></div>
      <div className="surface eval-proxy"><div className="surface-heading"><div><span className="eyebrow">SAVED 24-CATEGORY LABEL PROXY</span><h2>Category-label agreement</h2></div><span>{new Date(data.category_proxy.generated_utc).toLocaleDateString()}</span></div><div className="disclosure" role="note"><strong>Category-label agreement is not job-match accuracy.</strong> These titles act as queries and exact dataset labels act as weak proxies. They are separate from the three judged JDs.</div><p>{data.category_proxy.method} The saved check covers {data.category_proxy.shared_candidates.toLocaleString()} shared CSV candidates.</p><p className="table-scroll-hint">Scroll sideways to see all columns.</p><div className="category-table-wrap" role="region" aria-label="Saved category label proxy table" tabIndex={0} onKeyDown={keyboardScroll}><table className="category-table"><thead><tr><th scope="col">Category</th><th scope="col">Keyword label P@5</th><th scope="col">Hybrid label P@5</th><th scope="col">Keyword label nDCG@5</th><th scope="col">Hybrid label nDCG@5</th></tr></thead><tbody>{data.category_proxy.categories.map(item => <tr key={item.category}><th scope="row">{item.category}</th><td>{item.keyword.precision_at_5.toFixed(2)}</td><td>{item.hybrid.precision_at_5.toFixed(2)}</td><td>{item.keyword.ndcg_at_5.toFixed(3)}</td><td>{item.hybrid.ndcg_at_5.toFixed(3)}</td></tr>)}</tbody></table></div></div>
    </section>
    <section id="methodology" className="surface eval-section"><span className="eyebrow">07 / METHODOLOGY & LIMITS</span><h2>Reproduce and interpret</h2><p>Ranking: <code>python -m evaluation.score_labels</code> recomputes <code>metrics.json</code> from <code>labels.csv</code> and <code>review_pool_manifest.json</code>. Scale: <code>python -m evaluation.verify_full_import</code> checks the local CSV and database. Performance: <code>python -m evaluation.benchmark</code> creates a new local timing snapshot; the displayed values come from <code>benchmark_full.json</code>. Evidence: <code>python -m evaluation.audit_claims</code> checks <code>claim_audit.csv</code>; the seven gap observations are in <code>gap_status_audit.csv</code>. Category proxy: <code>python -m evaluation.category_proxy</code>.</p><p>{data.judgment_method} The labels were assigned after viewing output, so they are subject to implementer judgment bias. The 18-person pools, HR regression, and mention-only evidence limit any generalization. <strong>Not measured:</strong> full-corpus recall, independent hiring accuracy, fairness, concurrent-load behavior, or chatbot accuracy.</p></section>
  </div>
}
